### ISSUE TITLE
mergeUnique() doesn't remove an object from source

### ISSUE THREAD

**Issue by maks-humeniuk** [koresar/supermixer#10]
Hello.

Could you please help me to use your library for my special case?

Here's the demo: https://stackblitz.com/edit/js-b8f9qe?file=index.js.

Basically, both yours and Lodash `merge()` remove the object from source, but keep duplicate values.
`mergeUnique()` doesn't do that, but has no duplicates.

**Comment by koresar** [comment]
Hello. Demo is `404` already. Sorry.
And I do not understand what's the issue.
Next time just paste the whole code into the issue.
