### ISSUE TITLE
Why should I use this

### ISSUE THREAD

**Issue by troutowicz** [koresar/supermixer#4]
What reasons are there to user supermixer over utility libraries like lodash? I realize supermixer uses lodash, but what does this utility do better or simpler that lodash does not do on it's own?

**Comment by koresar** [comment]
Thank you very much for the question. I got it answered in the version 1 of this module. Please, see the top of the README.md :)

---

Unlike underscore/lodash utility methods this module allows you to:
- mix or deep merge objects' **prototype chain**. Regular mixin/extend/assign implementations can't do that.
- mix or deep merge **unique** properties only. I.e. data will **not be overwritten** if a property already exists.
- filter each individual property by **target value**, **source value**, and **key**. See API.
- transform each value by **resulting value**, **source value**, and **key**. See API.
