### ISSUE TITLE
Support the Symbol for mixing properties

### ISSUE THREAD

**Issue by danielkcz** [koresar/supermixer#6]
Comes from `stampit` and following code:

```
const mySymbol = Symbol();
const stamp = stampit().refs({ [mySymbol]: true });
const instance = stamp.create();
instance[mySymbol] === true; // FALSE
```

I am unable to find correct spot in the code, but it should probably utilize `Object.getOwnPropertySymbols` to make it working.

Edit: I suppose it's because of using `lodash.forEach` which doesn't support Symbol in general, so it going to need own implementation there.

**Comment by koresar** [comment]
Thanks for the request. Let's move the discussion over here: https://github.com/stampit-org/stamp-specification/issues/86
